<template>
	<div class="the-lining bg-wood">

		<div id="collapseUserForm" class="collapse">
			<center class="almond-bar inner-lining-m"><br><br>
			<div class="col-md-2"></div>
			<div class="col-md-8 inner-lining-m" style="background-color:#333;color:#4CAF50">
				<p class="text-warn" v-if="errors_msg != ''">{{errors_msg}}</p>
				<form @submit.prevent="validateBeforeSubmit">
				  <div class="form-row form-group">
				      <label class="col-md-3 col-lg-2 left">Slug</label>
				      <div  class="col-md-9 col-lg-10">
				      <input type="text" class="form-control" name="slug" v-model="slug" 
				      placeholder="< generated by system >" disabled>
				  	  </div>
				  </div>
				  <div class="form-row form-group">
				      <label class="col-md-3 col-lg-2 left">Title</label>
				      <div  class="col-md-9 col-lg-10">
				      <input type="text" class="form-control" name="title" v-model="title" :disabled="formDisabled" v-validate="'required'">
				      <span>{{ errors.first('title') }}</span>
				  	  </div>
				  </div>
				  <div class="form-row form-group">
				      <label class="col-md-3 col-lg-2 left">Excerpts</label>
				      <div  class="col-md-9 col-lg-10">
				      <input type="text" class="form-control" name="excerpts" v-model="excerpts" :disabled="formDisabled" v-validate="'required'">
				      <span>{{ errors.first('excerpts') }}</span>
				  	  </div>
				  </div>
				  <div class="form-row form-group">
				      <label class="col-md-3 col-lg-2 left">Body</label>
				      <div  class="col-md-9 col-lg-10">
				      <textarea class="form-control" rows="5" name="body" v-model="body" :disabled="formDisabled" v-validate="'required'"></textarea>
				      <span>{{ errors.first('body') }}</span>
				  	  </div>
				  </div>
				  <p v-if="loadingForm"><img src="/assets/images/loading-orange.gif" width="100px"></p>
				  <p v-else><button type="submit" :disabled="formDisabled">{{commandForm}}</button></p>
				</form>
			</div>
			<div class="col-md-2"></div>
			</center>
		</div>

		<div class="inner-lining-m curve-btm" style="background-color:#534038; color:#f2d2ab">
		<center>
		<strong type="button" class="btn btn-success" style="float:right" data-toggle="collapse" data-target="#collapseUserForm" @click="clearForm">
		Add New Articles</strong><br><br>
		<div class="huge"  id="main"> Blo<u>ody Moo</u>ldy </div>
			<br><br>
			<button v-on:click="showArticles">{{commandData}}</button>
			<br><br><br><br>
			<div v-if="loadingData">
				<img src="/assets/images/loading-orange.gif" width="100px">
			</div>
		</center>
		<div v-for="(value, idx) in data" class="inner-lining-s curve-all" style="background-color:#333">
			<strong type="button" class="btn btn-warning" style="float:right" @click="warningBeforeDelete(idx)">
			Delete</strong>
			<strong type="button" class="btn btn-success" style="float:right" @click="triggerCollapse(idx, value.id)">
			<!-- kalau sdh trigger by function gk usah pake toggle setting lg -->Edit</strong>
			<h2><a :href="'#'+value.slug">{{value.title}}</a></h2>
			<i>updated by {{value.user.fullname}}</i><br><br>
			<p v-html="value.body"></p><hr>
		</div>
		<div v-if="commandData != 'Get Data'" class="inner-lining-s curve-all" style="background-color:#333">
			<br>
	      	<div class="float-right">
		        <paginate
		          :pageCount="last_page"
		          :containerClass="'pagination'"
		          :page-class="'page-item'"
		          :page-link-class="'page-link'"
		          :prev-class="'page-item'"
		          :prev-link-class="'page-link'"
		          :next-class="'page-item'"
		          :next-link-class="'page-link'"
		          :clickHandler="clickCallback">
		        </paginate>
	     	</div>
			<br><br><br>
     	</div>
		</div>
	</div>
</template>

<script>
	import * as NETWORK from '../network/article.apiclient'

	export default{
		name: 'articles',
		components:{
		},
		data(){
			return {
				commandForm: "Add New Article",
				commandData: "Get Data",
				loadingForm: false,
				loadingData: false,
		        formDisabled: false,
				limit_data: 5,
				last_page: 0,
				current_page: 1,
		        errors_msg: '',
				data: [],
				id: 0,
				title: '',
				slug: '',
				excerpts: '',
				body: '',
		        id_selected: 0,
			}
		},
		methods:{
			getData: function(page){
				this.loading = true
				NETWORK.GET_ARTICLE(this.$store.getters.getToken, this.limit_data, page)
				.then((res)=>{
					this.data = res.data.data.articles
					this.current_page = res.data.data.paginator.current_page
					this.last_page = res.data.data.paginator.total_pages
					this.commandData = "Hide Result"
				}, (err)=>{
					this.handleAPI(err)
				})
				this.loading = false
			},
			showArticles(){
				if(typeof this.data !== 'undefined' && this.data.length > 0){
					this.data = []
					this.commandData = "Get Data"
				}else{
					this.getData(1)
				}
			},
			clickCallback(page){
		        this.current_page = page
		        this.getData(page)
			},
			validateBeforeSubmit(page){
				//slug created automaticly
		        this.$validator.validateAll().then((result) => {
		          if (result) {
		            var params = new URLSearchParams();
		            var slug = this.title.toLowerCase();
		            slug = slug.replace(/[^A-Za-z0-9_]/,""); //eliminate punctuation
		            slug = slug.replace(/\ /g,"-"); //change space into stripes
		            slug = this.id + "_" + slug; //id in the very first for unique identifier at same title case
		            params.append('slug', slug);
		            params.append('id', this.id);
		            params.append('title', this.title);
		            params.append('excerpts', this.excerpts);
		            params.append('body', this.body);
		            // this.formDisabled = true
		            this.loadingForm = true
		            if(this.id === 0){
						NETWORK.ADD(this.$store.getters.getToken, params).then((res)=>{
							if(typeof res.data.data.id === 'undefined' || res.data.data.id === null){}
							else{}
							alert("SUCCED")
							this.clearForm()
							this.getData(this.current_page)
							this.loadingForm = false
						}, (err)=>{
							this.loadingForm = false
							this.handleAPI(err)
						})
		            }else{
						NETWORK.UPDATE(this.$store.getters.getToken, params).then((res)=>{
							alert("SUCCED", "\n",res.data.data)
							this.clearForm()
							this.getData(this.current_page)
							this.loadingForm = false
						}, (err)=>{
							this.loadingForm = false
							this.handleAPI(err)
						})
		            }
		            return;
		          }
		        });
			},
			clearForm(){
				this.id = 0
		        this.title = ''
		        this.slug = ''
		        this.excerpts = ''
		        this.body = ''
				console.log("cleaning ... DONE")
			},
			triggerCollapse(idx, id_user){
				let classDefined = document.getElementById("collapseUserForm").className;
				if(classDefined == "collapse" || (this.id_selected != 0 && this.id_selected != id_user)){
					this.id = this.data[idx].id
			        this.title = this.data[idx].title
			        this.slug = this.data[idx].slug
			        this.excerpts = this.data[idx].excerpts
			        this.body = this.data[idx].body
					this.commandForm = "Update Article Info"
					this.id_selected = this.id 
					document.getElementById("collapseUserForm").className = "collapse show";
				}else{
					this.clearForm()
					document.getElementById("collapseUserForm").className = "collapse";
				}
			},
			warningBeforeDelete(idx){
				if (confirm('Are you sure to delete "'+ this.data[idx].title + 
					'"\n [id ::' + this.data[idx].id + ']')) {
					NETWORK.DELETE(this.$store.getters.getToken, this.data[idx].id).then((res)=>{
						alert("Deleted successfully")
						this.getData(this.current_page)
					}, (err)=>{
						alert("Delete failed")
					})
				}
				else {
				    console.log('article undeleted')
				}
			},
		}
	};
</script>